#!/usr/bin/env python

# Add strings to the exception's notes list with `add_note()`
# try:
#     raise TypeError('bad type')
# except Exception as e:
#     e.add_note('Add some information')
#     e.add_note('Add some more information')
#     raise

def f():
    raise OSError('operation failed')

# Show an iteration when the exceptions have occurred
excs = []
for i in range(3):
    try:
        f()
    except Exception as e:
        e.add_note(f'Happened in Iteration {i+1}')
        excs.append(e)

raise ExceptionGroup('We have some problems', excs)
